### ISSUE TITLE
Must install jade-brackets locally?

### ISSUE THREAD

**Issue by luozt** [ForbesLindesay/jade-brackets#25]
Must this jade-brackets module be installed locally? Not globally? It did not work when I `npm i -g jade-highlighter` which made my project dir would always have a `node_modules` dir. It makes me not feel good.

**Comment by ForbesLindesay** [comment]
To do what?  What are you using the module for?  If you're using it to add syntax highlighting to the brackets editor, just use the brackets package manager.  If you're using it for other syntax highlighting purposes then you should install it and use it locally.

**Comment by luozt** [comment]
I'm using `fis-parser-jade` and `jade-highlighter` to compile jade templates. `jade-highlighter` must be only npm install locally in project dir that it can works when other npm modules installed globally, which leads to every working place has a `node_modules` dir with only one module `jade-highlighter`. Hope this can be improved!~

**Comment by ForbesLindesay** [comment]
I have no idea what you mean.  If you're using jade-highlighter locally as part of your project, you should install it locally (that's just good practice so you can easily share your project and keep track of what it requires).  If you're using jade-highlighter as part of some command line tool-chain then you should install it globally, but since it doesn't come with a CLI, it should probably just be a dependency of whatever command line interface you're using to call it.

**Comment by luozt** [comment]
Eh, my poor english.-_-#||. But this sentence you said 「If you're using jade-highlighter locally as part of your project, you should install it locally (that's just good practice so you can easily share your project and keep track of what it requires). 」 addresses my problem. I have got it! Thanks!
